<!-- Single Column Form -->
<form action="[REPLACE]" class="ibm-column-form ibm-styled-form" enctype="multipart/form-data" method="post">
<p><label for="Salutation">Salutation:<span class="ibm-required">*</span>
<span class="ibm-item-note">(e.g., Mr., Mrs.)</span></label>
<span><select name="salutation" id="Salutation">
<option value="" selected="selected">Select one</option>
<option value="Mr.">Mr.</option>
<option value="Mrs.">Mrs.</option>
<option value="Ms">Ms.</option>
<option value="Miss">Miss</option>
<option value="Dr.">Dr.</option>
</select></span></p>
<p><label for="First_name">First name:<span class="ibm-required">*</span></label><span><input name="first_name" id="First_name" size="40" type="text" value=""/></span></p>
<p><label for="Last_name">Last name:<span class="ibm-required">*</span></label>
<span><input name="last_name" id="Last_name" size="40" type="text" value=""/></span></p>
<p><label for="E_mail_address">E-mail address:<span class="ibm-required">*</span></label><span><input name="email" id="E_mail_address" size="40" type="text" value=""/></span></p>
<p><label for="Phone_number">Phone number:</label><span><input name="phone_number" id="Phone_number" size="40" type="text" value=""/></span></p>
<p><label for="Country_region">Country / region:<span class="ibm-required">*</span></label>
<span><select class="iform" name="usercc" id="Your_country_or_region">
<option value="" selected="selected">Please select one</option>
<option value="us">United States</option>
<option value="ar">Argentina</option>
<option value="au">Australia</option>
<option value="at">Austria</option>
<option value="bs">Bahamas</option>
<option value="bh">Bahrain</option>
<option value="bb">Barbados</option>
<option value="be">Belgium</option>
<option value="bm">Bermuda</option>
<option value="bo">Bolivia</option>
<option value="bw">Botswana</option>
<option value="br">Brazil</option>
<option value="bg">Bulgaria</option>
<option value="ca">Canada</option>
<option value="cl">Chile</option>
<option value="cn">China</option>
<option value="co">Colombia</option>
<option value="hr">Croatia</option>
<option value="cy">Cyprus</option>
<option value="cz">Czech Republic</option>
<option value="dk">Denmark</option>
<option value="do">Dominican Republic</option>
<option value="ec">Ecuador</option>
<option value="eg">Egypt</option>
<option value="sv">El Salvador</option>
<option value="ee">Estonia</option>
<option value="fi">Finland</option>
<option value="fr">France</option>
<option value="de">Germany</option>
<option value="gr">Greece</option>
<option value="gt">Guatemala</option>
<option value="hn">Honduras</option>
<option value="hk">Hong Kong S.A.R. of China</option>
<option value="hu">Hungary</option>
<option value="in">India</option>
<option value="id">Indonesia</option>
<option value="ie">Ireland</option>
<option value="il">Israel</option>
<option value="it">Italy</option>
<option value="jm">Jamaica</option>
<option value="jp">Japan</option>
<option value="jo">Jordan</option>
<option value="kr">Korea, Republic of</option>
<option value="kw">Kuwait</option>
<option value="lv">Latvia</option>
<option value="lb">Lebanon</option>
<option value="lt">Lithuania</option>
<option value="my">Malaysia</option>
<option value="mx">Mexico</option>
<option value="ma">Morocco</option>
<option value="nl">Netherlands</option>
<option value="an">Netherlands Antilles</option>
<option value="nz">New Zealand</option>
<option value="ni">Nicaragua</option>
<option value="no">Norway</option>
<option value="om">Oman</option>
<option value="pk">Pakistan</option>
<option value="pa">Panama</option>
<option value="py">Paraguay</option>
<option value="pe">Peru</option>
<option value="ph">Philippines</option>
<option value="pl">Poland</option>
<option value="pt">Portugal</option>
<option value="qa">Qatar</option>
<option value="ro">Romania</option>
<option value="ru">Russian Federation</option>
<option value="sa">Saudi Arabia</option>
<option value="sn">Senegal</option>
<option value="yu">Serbia and Montenegro</option>
<option value="sg">Singapore</option>
<option value="sk">Slovakia</option>
<option value="si">Slovenia</option>
<option value="za">South Africa</option>
<option value="es">Spain</option>
<option value="lk">Sri Lanka</option>
<option value="sr">Suriname</option>
<option value="se">Sweden</option>
<option value="ch">Switzerland</option>
<option value="tw">Taiwan</option>
<option value="th">Thailand</option>
<option value="tt">Trinidad and Tobago</option>
<option value="tn">Tunisia</option>
<option value="tr">Turkey</option>
<option value="ae">United Arab Emirates</option>
<option value="uk">United Kingdom</option>
<option value="us">United States</option>
<option value="uy">Uruguay</option>
<option value="ve">Venezuela</option>
<option value="vn">Vietnam</option>
</select></span></p>
<p><label for="Job_role">Job role:</label>
<span><select name="profile" id="Help_us_answer_your_message">
<option value="" selected="selected">Which best describes you?</option>
<option value="Business_user">Business user</option>
<option value="Consultant">Consultant</option>
<option value="Employee">Employee</option>
<option value="Home_user">Home user</option>
<option value="IT_purchaser">IT purchaser</option>
<option value="Prospective_customer">Prospective customer</option>
<option value="Reseller">Reseller</option>
<option value="Software_developer">Software developer</option>
<option value="Stockholder">Stockholder</option>
<option value="Student">Student</option>
<option value="Other">Other</option>
</select></span></p>
<p><label for="category">Message category:<span class="ibm-required">*</span></label>
<span><select name="category" id="category">
<option value="">Select one</option>
<option value="Government and Education">Government and Education</option>
<option value="IBM Business Partners">IBM Business Partners</option>
<option value="IBM Global Services">IBM Global Services</option>
<option value="IBM Learning Services">IBM Learning Services</option>
<option value="Industry solutions">Industry solutions</option>
<option value="IT security">IT security</option>
<option value="Jobs at IBM">Jobs at IBM</option>
<option value="Midrange/Mainframe servers">Midrange/Mainframe servers</option>
<option value="Personal Systems">Personal Systems</option>
<option value="Privacy">Privacy</option>
<option value="Research and development">Research and development</option>
<option value="Search feedback">Search feedback</option>
<option value="Software">Software</option>
<option value="Student inquiries">Student inquiries</option>
<option value="Web site feedback">Web site feedback</option>
<option value="Other">Other</option>
</select></span></p>
<p><label for="Is_this_a_complaint_">Is this a complaint?</label><span><input type="checkbox" name="complaint" id="Is_this_a_complaint_" value="Yes"/>Yes</span></p>
<p><label for="Subject">Subject:</label><span><input name="subject" id="Subject" size="40" type="text" value=""/></span></p>
<p><label for="Message">Message:<span class="ibm-required">*</span></label><span><textarea id="Message" cols="38" rows="7" name="message"></textarea></span></p>
<div class="ibm-alternate-rule"><hr></div>
<p>Country specific privacy and notice & choice statement. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
<div class="ibm-rule"><hr></div>
<div class="ibm-buttons-row">
<p><input value="Submit" type="submit" name="ibm-submit" class="ibm-btn-arrow-pri" /></p>
</div>
</form> 