<div id="ibm-content">
<!-- CONTENT_BODY -->
<div id="ibm-content-body">
<div id="ibm-content-main">
<p class="ibm-rht-hide">
	<span class="ibm-error-link">The sign in attempt failed. You may have incorrectly entered your Intranet e-mail ID or password. Please try again using a valid user ID and password. If you have forgotten your password, please contact with <a href="mailto:someone@cn.ibm.com">Administrator</a> to change or reset your password.</span>
</p>
<p>Please sign in using your Intranet address as listed in <a href="https://w3.ibm.com/bluepages/">Blue Pages</a>. Alternate Intranet addresses and aliases can not be used.</p>

<form action="login.html" class="ibm-column-form ibm-styled-form" enctype="multipart/form-data" method="post" id="ibm-rht-login" >
	<p>
		<label for="ibm-rht-id">Intranet ID:</label>
		<input name="id" id="ibm-rht-id" size="40" type="text" value="" placeholder="e.g., zhaosk@cn.ibm.com">
			</p>
	<p>
		<label for="ibm-rht-password">Password:</label>
		<input name="password" id="ibm-rht-password" size="40" type="password" value="">
		<br />
		<a href="javascript:;">Forgot your password?</a>
	</p>
	<div class="ibm-rule"><hr/></div>
	<div class="ibm-buttons-row">
		<p>
			<input value="Submit" type="submit" name="submit" class="ibm-btn-arrow-pri" /><span class="ibm-sep">&nbsp;</span> 
			<input value="Cancel" type="submit" name="ibm-cancel" class="ibm-btn-cancel-sec" />
		</p>
	</div>
</form>
</div>
<!-- FEATURES_BEGIN -->
<div id="ibm-content-sidebar">
<div id="ibm-contact-module">
<!--IBM Contact Module-->
</div>
%%sidebarspace%%
</div>
<!-- FEATURES_END -->
<!-- CONTENT_BODY_END -->
</div>
</div>