<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="schema.DC" href="http://purl.org/DC/elements/1.0/"/>
<link rel="SHORTCUT ICON" href="http://w3.ibm.com/favicon.ico"/>
<meta name="DC.Rights" content="© Copyright IBM Corp. 2011"/>
<meta name="Keywords" content="Hiring tool"/>
<meta name="DC.Date" scheme="iso8601" content="2012-04-13"/>
<meta name="Source" content="v17 Template Generator, Template 17.02"/>
<meta name="Security" content="Public"/>
<meta name="Abstract" content="This tool is designed for help Tools org with hiring process."/>
<meta name="IBM.Effective" scheme="W3CDTF" content="2012-04-13"/>
<meta name="DC.Subject" scheme="IBM_SubjectTaxonomy" content="REPLACE"/>
<meta name="Owner" content="Shi Kai Zhao/China/IBM"/>
<meta name="DC.Language" scheme="rfc1766" content="en-US"/>
<meta name="IBM.Country" content="US"/>
<meta name="Robots" content="index,nofollow"/>
<meta name="DC.Type" scheme="IBM_ContentClassTaxonomy" content="REPLACE"/>
<meta name="Description" content="This tool is designed for help Tools org with hiring process."/>

<title>IBM Rapid Hiring Tool</title>
<link href="//1.w3.s81c.com/common/v17/css/w3.css" rel="stylesheet" title="w3" type="text/css" />
<link rel="stylesheet" href="/css/common.css" />
<link rel="stylesheet" href="/css/login.css" />
<script src="//1.w3.s81c.com/common/js/dojo/1.6/w3.js" type="text/javascript">//</script>
</head>
<body id="ibm-com" class="ibm-rht ibm-liquid">
<div id="ibm-top">

<!-- MASTHEAD_BEGIN -->
<div id="ibm-masthead">
<div id="ibm-mast-options">
<ul>
<li id="ibm-home"><a href="http://w3.ibm.com/">w3</a></li>
</ul>
</div>
<div id="ibm-universal-nav">
<p id="ibm-site-title"><em>Rapid Hiring Tool</em></p>
<ul id="ibm-menu-links">
<li><a href="http://w3.ibm.com/sitemap/us/en/">Site map</a></li>
</ul>
<div id="ibm-search-module">
<form id="ibm-search-form" action="http://w3.ibm.com/search/do/search" method="get">
<p>
<label for="q"><span class="ibm-access">Search</span></label>
<input type="text" maxlength="100" value="" name="qt" id="q"/>
<input type="hidden" value="17" name="v"/>
<input value="en" type="hidden" name="langopt"/>
<input value="all" type="hidden" name="la"/>
<input type="submit" id="ibm-search" class="ibm-btn-search" value="Submit"/>
</p>
</form>
</div>
</div>
</div>
<!-- MASTHEAD_END -->

<div id="ibm-pcon">
<!-- CONTENT_BEGIN -->
<div id="ibm-content">
<div id="ibm-leadspace-head" class="ibm-alternate">
<div id="ibm-leadspace-body">
<h1>Rapid Hiring Tool</h1>
</div>
</div>
<!-- CONTENT_BODY -->
<div id="ibm-content-body">
<div id="ibm-content-main">
%% main content space %%
<?php echo $this->layout()->content;?>
</div>
<!-- FEATURES_BEGIN -->
<div id="ibm-content-sidebar">
<div id="ibm-contact-module">
<!--IBM Contact Module-->
</div>
<div id="ibm-merchandising-module">
<!--IBM Web Merchandising Module-->
</div>
%% sidebar space %%
<!-- require sidebar phtml -->
</div>
<!-- FEATURES_END -->
<!-- CONTENT_BODY_END -->
</div>
</div>
<!-- CONTENT_END -->
<!-- NAVIGATION_BEGIN -->
<?php echo $this->partial('leftnav.layout.phtml', array(
							'menuClass' => $this->menuClass, 
							)
						); 
?>
<!-- require leftnav phtml -->
<!-- NAVIGATION_END -->
</div>
<div id="ibm-related-content"></div>

<!-- FOOTER_BEGIN -->
<div id="ibm-footer-module">
</div>
<div id="ibm-footer">
<h2 class="ibm-access">Footer links
</h2>
<ul>
<li><a href="http://w3.ibm.com/w3/info_terms_of_use.html">Terms of use</a></li>
</ul>
</div>
<!-- FOOTER_END -->
</div>
<div id="ibm-metrics">
<script src="//w3.ibm.com/w3webmetrics/js/ntpagetag.js" type="text/javascript">//</script>
</div>
</body>
</html>
